### ISSUE TITLE
[doc]: Sprint Backlog estimations (2/2)

### ISSUE THREAD

**Issue by AntonioRodriguezRuiz** [ISPP-07/htld-doc#105]
Frontend, Management and Marketing

**Comment by Marchabar** [comment]
@josgarber6 you are in charge of reviewing this task.

**Comment by josgarber6** [comment]
Where is that doc please?

**Comment by Marchabar** [comment]
> Where is that doc please?

ISPP Drive > documents > Product Backlog Excel

**Comment by josgarber6** [comment]
Aparently, the estimation has been done correctly.

**Comment by Marchabar** [comment]
> Aparently, the estimation has been done correctly.

Then, we can close this issue
