### ISSUE TITLE
[dev]: Create landing page

### ISSUE THREAD

**Issue by Marchabar** [ISPP-07/htld-doc#125]
- [x] It would be interesting to add the teams we are, links to our repositories, deployments (taking into account that there will be different versions of the backend and frontend deployed -> 1 per Sprint).
- [x] Have a hook phrase that sells us as **Harmony**.
- [x] Basically, a simple page that is like a letter of introduction to potential investors to get to know our company "Harmony".
- [x] Use a simple technology that helps you with the task

**Comment by alvarobernal2412** [comment]
The first version of the landing page has been created at the following URL and will be reviewed before being included in the presentations. 

https://alvarobc2412.wixsite.com/harmony-ltd

**Comment by alejandromd** [comment]
The landing page is very nice, I think it covers everything that a page with our main information should have. You have done a great job.
