### ISSUE TITLE
conf: Standardise the boards

### ISSUE THREAD

**Issue by AntonioRodriguezRuiz** [ISPP-07/htld-doc#155]
This task aims to unify with the rest of the repositories the way of managing the tasks, so that the rest of the repositories manage their tasks in the same way as we currently do. It is important to bear in mind that it may be necessary to record an explanatory video or modify some methodology. For example:
Changes issues from `Make ACAT responsive` to `feat: Make ACAT responsive`

**Comment by AntonioRodriguezRuiz** [comment]
Boards added to the organization, made public and "closed" the previous ones.

Videos of the [Backend Project](https://drive.google.com/file/d/1kbFjo9fLlXwmDwhdWhAxJT357NH1HVc4/view?usp=drive_link) and [Frontend Project](https://drive.google.com/file/d/1M98gC4QhSwRgcqzv4Ef8cP3YqKA1MEdr/view?usp=drive_link) have been made available

**Comment by Marchabar** [comment]
@josgarber6 is the reviewer for this issue.

**Comment by josgarber6** [comment]
It's amazing to see how well organized is everything right now. Accessing to the tasks and estimations is way easier and of course knowing which task need testing. Excellent work mate!!
