### ISSUE TITLE
doc: Include pilot users calendars

### ISSUE THREAD

**Issue by AntonioRodriguezRuiz** [ISPP-07/htld-doc#169]
> [!IMPORTANT]
>  - First, see the relevant information from the 07-pilots.pdf document for inclusion in the docusaurus as well from drive.
> - Important to add some visual resources.
- As other groups have done, it would be interesting to include a Sprint 2 calendar with:
  - Dates on which we have delivered the app to the pilot users (Put with representative images to which pilot user the application has been delivered).
  - Intervals in which they have tested the app
  - Date on which they gave us feedback
  - Date on which we have analysed this feedback
- Calendar of Sprint 3 with a schedule with the same points as those mentioned in Sprint 2. 
- Feedback management

**Comment by Marchabar** [comment]
@josgarber6 is the reviewer of this task
