### ISSUE TITLE
doc: Calendar research

### ISSUE THREAD

**Issue by alvarobernal2412** [ISPP-07/htld-doc#186]
Investigate whether it is possible to improve the scheduling to automate the search for availability at meetings for members of the group or for the whole group. The idea you have given in class is that we share our calendars but this cannot be done as there are people who do not use it. **Important to see if there is an alternative that would make us achieve that goal in a different way.**

**Comment by alvarobernal2412** [comment]
## Some discoveries
After researching a few meeting scheduling applications, the easiest one I have found is [calendly](https://calendly.com). Meetings can be held there quickly and easily. You only need to register and attach your availability schedule (It's very simple). **See image below:**
    <img src="https://github.com/ISPP-07/htld-doc/assets/80347035/b21ea9bd-c612-4f3d-a0f9-c1355aedf287" alt="Image" width="300px">

Afterwards, a meeting is created and shows you the windows available for the guests. **See image below:**
![Image](https://github.com/ISPP-07/htld-doc/assets/80347035/e327b253-a7ef-4780-a8c9-a1c9aca1fd87)

The positive thing about this tool is that it does not oblige users to link a personal calendar or to make use of any of these calendars, they only need to include their weekly availability.

**Comment by AntonioRodriguezRuiz** [comment]
@alvarobernal2412 can it be synced with other calendar applications?

**Comment by alvarobernal2412** [comment]
@AntonioRodriguezRuiz Yes, you can connect Google calendar in addition to meeting tools like zoom or Google meet.

**Comment by AntonioRodriguezRuiz** [comment]
Good
