### ISSUE TITLE
doc: Add PPL planning

### ISSUE THREAD

**Issue by josgarber6** [ISPP-07/htld-doc#257]
Add to the "Planning" section a planning section including current S3 planning and PPL planning. The image to be attached must be very clear and simple. If you make a gantt, make it very simple and visible or use a calendar with representative icons (if there are many of them, add a legend).

**Comment by josgarber6** [comment]
Current S3 planning is already on the docusaurus page, should I update it, or is it updated till now? @alvarobernal2412

**Comment by alvarobernal2412** [comment]
You should include the pilot users RFCs @josgarber6
