### ISSUE TITLE
[feat]: Add search bar and AI use info to docs

### ISSUE THREAD

**Issue by sebasruii** [ISPP-07/htld-doc#28]

**Comment by sebasruii** [comment]
Mejorar el documento de la IA, haciendo un buscador desde nuestro
Vercel de Docusaurus. - He añadido una barra de búsqueda que permite navegar por la documentación, además de una nueva forma de registrar el uso de la IA en la propia documentación
https://htld-doc.vercel.app/
viernes 9 feb
20 min

**Comment by jmartinacu** [comment]
Revisado por Joaquin Martin
