### ISSUE TITLE
doc: Search engine optimization

### ISSUE THREAD

**Issue by davidg43** [ISPP-07/htld-doc#368]
Create a doc in the "Marketing" section in docusaurus for Search Engine Optimisation, you should research on SEO and SEM.

**Comment by davidg43** [comment]
I had some doubts about the content you need in this doc, so I prepared a general doc researching information about SEO and SEM and some tools to manage them.

**Comment by alvarobernal2412** [comment]
Due to the context of the project, this task will not be added to docusaurus. Still, thank you for your time and effort!
