### ISSUE TITLE
marketing: print, crop and distribute

### ISSUE THREAD

**Issue by AntonioRodriguezRuiz** [ISPP-07/htld-doc#448]
Your job is to print, crop and distribute the following design throughout the whole ETSII. Each of you should print 20-30 copies at least. 

IMPORTANT: The size has not been tested. So you should first print one and see if its the size of an iphone( approximately, it does not have to be exact). You have to print this in the paper normally used to print flyers, NOT normal paper.

![Image](https://github.com/ISPP-07/htld-doc/assets/74500641/6166218c-be1b-43d9-90b5-65b31b2b8a04)

**Comment by alvarobernal2412** [comment]
Well done!
