### ISSUE TITLE
[doc]: Pilot users management

### ISSUE THREAD

**Issue by alvarobernal2412** [ISPP-07/htld-doc#93]
- Including the windows of availability that NGOs and group 1 tomorrow will have to test the app (important to meet this window in reality), and define a feedback collection and feedback analysis window to check if changes, re-planning, etc. have to be done...
- Customer support:  Formula to see the support (Maintenance plan). Depending on the TTR, staff needed and price needed depending on the type of availability. AI support, human support.

**Priority: Medium**

**Comment by AntonioRodriguezRuiz** [comment]
Wouldn't the customer support point be part of the TCO?

**Comment by AntonioRodriguezRuiz** [comment]
There is a document to base this on already in google drive
