### ISSUE TITLE
[doc]: Individual performance

### ISSUE THREAD

**Issue by alvarobernal2412** [ISPP-07/htld-doc#94]
- A formula that gives the overall score that varies according to the role as the "Care for ME" group. Within that formula if history points are taken into account it should be multiplied by a "quality of estimate percentage". **Interesting to look at the BGCC from previous years for formulas**.
- Make a weekly performance table for each person (not anonymous, it will be anonymous in the presentation). Highlight the person with the best performance and the person with the biggest improvement from one week to the next.
- In markdown you can use latex code to create formulas, for example: $$\sum_{i=1}^{4} x_{ij}v_i \leq v_j\forall j$$
**Priority: High**

**Comment by Ronald752** [comment]
[https://docs.google.com/document/d/1HzxxdThfzzxoqi7qFGhZYKarfPA8YA9SSk9vAc4j-4U/edit#heading=h.vawpvfxv5v3f](Measuring performance)

**Comment by AntonioRodriguezRuiz** [comment]
I liked the new performance metrics a lot, done per individual. I will request tho to remove the **TA** metric which will be of no use now, and the **RIP** and **RPG**, since now we have other metrics to evaluate the performance of the team members

**Comment by AntonioRodriguezRuiz** [comment]
@Ronald752
