### ISSUE TITLE
[conf]: iTop initialisation

### ISSUE THREAD

**Issue by alvarobernal2412** [ISPP-07/htld-doc#98]
We should make it available as soon as possible for pilot users and for next week's PPTX.
**Priority: High**

**Comment by AntonioRodriguezRuiz** [comment]
I could not meet the deadline due to the server not being yet up

**Comment by AntonioRodriguezRuiz** [comment]
Things included in the iTop configuration:
- Callers for requests, problems and issues (G1, G7, ACAT, CyC)
- Services for CyC and ACAT along with subservices for frontend and backend (useful for reporting errors)
- Application Solutions to relate the services with more stuff down the road
- Backend, Frontend and devops teams to assign problems and tasks to.

**Screenshots**

![Image](https://github.com/ISPP-07/htld-doc/assets/73228905/5c3c932a-741e-4db9-9771-02f3e1898862)

![Image](https://github.com/ISPP-07/htld-doc/assets/73228905/0d5c74e2-5d41-481c-8240-d5ff28cc74a6)

![Image](https://github.com/ISPP-07/htld-doc/assets/73228905/ccfe359a-6874-4eab-ad55-57af1dabfdba)

![Image](https://github.com/ISPP-07/htld-doc/assets/73228905/fb8699bc-b1a1-44bc-9fac-ef9437fa7790)

**Comment by AntonioRodriguezRuiz** [comment]
The url is: https://oitilo.us.es/itop/pages/UI.php 
You have to login with SAML and go to the organization (Harmony)
